//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "api_key")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub merchant_id: String,
    pub name: String,
    pub key_prefix: String,
    pub key_hash: String,
    pub secret_hash: String,
    pub permissions: String,
    pub is_active: bool,
    pub last_used: Option<DateTimeWithTimeZone>,
    pub expires_at: Option<DateTimeWithTimeZone>,
    pub created_at: DateTimeWithTimeZone,
    pub encrypted_api_key: Option<String>,
    pub encrypted_secret_key: Option<String>,
    pub environment_type: String,
    pub api_key: Option<String>,
    pub secret_key: Option<String>,
    pub rate_limit_per_minute: Option<i32>,
    pub rate_limit_per_hour: Option<i32>,
    pub last_revoked_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::api_key_usage::Entity")]
    ApiKeyUsage,
    #[sea_orm(
        belongs_to = "super::merchant::Entity",
        from = "Column::MerchantId",
        to = "super::merchant::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Merchant,
}

impl Related<super::api_key_usage::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ApiKeyUsage.def()
    }
}

impl Related<super::merchant::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Merchant.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
