//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "compliance_check")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub transaction_hash: String,
    pub from_address: String,
    pub to_address: String,
    pub amount: Decimal,
    pub currency: String,
    pub risk_score: Decimal,
    #[sea_orm(column_type = "Text")]
    pub risk_factors: String,
    pub compliance_status: String,
    pub checked_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
