//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "merchant")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub user_id: String,
    pub name: String,
    pub description: Option<String>,
    pub website_url: Option<String>,
    pub webhook_url: Option<String>,
    pub webhook_secret: Option<String>,
    pub is_active: bool,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: Option<DateTimeWithTimeZone>,
    pub environment_type: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub preferred_networks: Option<String>,
    pub token_version: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::api_key::Entity")]
    ApiKey,
    #[sea_orm(has_many = "super::payment_request::Entity")]
    PaymentRequest,
    #[sea_orm(has_many = "super::payout_transaction::Entity")]
    PayoutTransaction,
    #[sea_orm(has_many = "super::settlement::Entity")]
    Settlement,
    #[sea_orm(has_many = "super::settlement_rule::Entity")]
    SettlementRule,
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::UserId",
        to = "super::user::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    User,
    #[sea_orm(has_many = "super::withdrawal_request::Entity")]
    WithdrawalRequest,
}

impl Related<super::api_key::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ApiKey.def()
    }
}

impl Related<super::payment_request::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PaymentRequest.def()
    }
}

impl Related<super::payout_transaction::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PayoutTransaction.def()
    }
}

impl Related<super::settlement::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Settlement.def()
    }
}

impl Related<super::settlement_rule::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SettlementRule.def()
    }
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

impl Related<super::withdrawal_request::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WithdrawalRequest.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
