//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "payment_request")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub merchant_id: String,
    pub external_id: Option<String>,
    pub amount: Decimal,
    pub currency: String,
    pub wallet_address: String,
    pub status: String,
    pub metadata: Option<String>,
    pub payment_url: Option<String>,
    pub expires_at: DateTimeWithTimeZone,
    pub paid_at: Option<DateTimeWithTimeZone>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: Option<DateTimeWithTimeZone>,
    pub environment: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::merchant::Entity",
        from = "Column::MerchantId",
        to = "super::merchant::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Merchant,
    #[sea_orm(has_many = "super::settlement::Entity")]
    Settlement,
    #[sea_orm(has_many = "super::transaction::Entity")]
    Transaction,
    #[sea_orm(has_many = "super::webhook_log::Entity")]
    WebhookLog,
}

impl Related<super::merchant::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Merchant.def()
    }
}

impl Related<super::settlement::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Settlement.def()
    }
}

impl Related<super::transaction::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Transaction.def()
    }
}

impl Related<super::webhook_log::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WebhookLog.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
