//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "settlement")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub merchant_id: String,
    pub payment_request_id: String,
    pub original_amount: Decimal,
    pub original_currency: String,
    pub settled_amount: Decimal,
    pub settled_currency: String,
    pub conversion_rate: Option<Decimal>,
    pub fee_amount: Decimal,
    pub fee_currency: String,
    pub status: String,
    pub payout_address: String,
    pub payout_network: String,
    pub payout_tx_hash: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub settled_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::merchant::Entity",
        from = "Column::MerchantId",
        to = "super::merchant::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Merchant,
    #[sea_orm(
        belongs_to = "super::payment_request::Entity",
        from = "Column::PaymentRequestId",
        to = "super::payment_request::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    PaymentRequest,
}

impl Related<super::merchant::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Merchant.def()
    }
}

impl Related<super::payment_request::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PaymentRequest.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
