//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "transaction")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub payment_request_id: String,
    pub tx_hash: String,
    pub block_number: Option<i64>,
    pub block_hash: Option<String>,
    pub from_address: String,
    pub to_address: String,
    pub amount: Decimal,
    pub currency: String,
    pub gas_used: Option<i64>,
    pub gas_price: Option<String>,
    pub confirmations: i32,
    pub status: String,
    pub network: String,
    pub created_at: DateTimeWithTimeZone,
    pub confirmed_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::payment_request::Entity",
        from = "Column::PaymentRequestId",
        to = "super::payment_request::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    PaymentRequest,
}

impl Related<super::payment_request::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PaymentRequest.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
