//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "wallet_balance")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub wallet_id: String,
    pub currency: String,
    pub available_balance: Decimal,
    pub pending_balance: Decimal,
    pub total_balance: Decimal,
    pub locked_balance: Decimal,
    pub last_updated: DateTimeWithTimeZone,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::wallet::Entity",
        from = "Column::WalletId",
        to = "super::wallet::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Wallet,
}

impl Related<super::wallet::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Wallet.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

impl Model {
    /// Get the total balance including locked funds
    pub fn get_total_with_locked(&self) -> Decimal {
        self.available_balance + self.pending_balance + self.locked_balance
    }

    /// Get the spendable balance (available but not locked)
    pub fn get_spendable_balance(&self) -> Decimal {
        self.available_balance - self.locked_balance
    }

    /// Check if there are sufficient available funds for a withdrawal amount
    pub fn has_sufficient_available(&self, amount: Decimal) -> bool {
        self.get_spendable_balance() >= amount
    }

    /// Check if there are locked funds
    pub fn has_locked_funds(&self) -> bool {
        self.locked_balance > Decimal::ZERO
    }
}
