//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "wallet")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub user_id: String,
    pub currency: String,
    pub address: String,
    pub public_key: String,
    pub private_key: String,
    pub mnemonic: String,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::deposit_tracking::Entity")]
    DepositTracking,
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::UserId",
        to = "super::user::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    User,
    #[sea_orm(has_many = "super::wallet_balance::Entity")]
    WalletBalance,
    #[sea_orm(has_many = "super::wallet_transaction::Entity")]
    WalletTransaction,
    #[sea_orm(has_many = "super::withdrawal_request::Entity")]
    WithdrawalRequest,
}

impl Related<super::deposit_tracking::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DepositTracking.def()
    }
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

impl Related<super::wallet_balance::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WalletBalance.def()
    }
}

impl Related<super::wallet_transaction::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WalletTransaction.def()
    }
}

impl Related<super::withdrawal_request::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WithdrawalRequest.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
