//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "webhook_log")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub payment_request_id: String,
    pub webhook_url: String,
    #[sea_orm(column_type = "Text")]
    pub payload: String,
    pub response_status: Option<i32>,
    #[sea_orm(column_type = "Text", nullable)]
    pub response_body: Option<String>,
    pub status: String,
    pub attempts: i32,
    pub next_retry_at: Option<DateTimeWithTimeZone>,
    pub created_at: DateTimeWithTimeZone,
    pub delivered_at: Option<DateTimeWithTimeZone>,
    pub merchant_id: String,
    pub event_type: String,
    pub last_attempt_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::payment_request::Entity",
        from = "Column::PaymentRequestId",
        to = "super::payment_request::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    PaymentRequest,
}

impl Related<super::payment_request::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PaymentRequest.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
