//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "withdrawal_request")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub merchant_id: String,
    pub wallet_id: String,
    pub external_id: String,
    pub idempotency_key: String,
    pub environment: String,
    pub network: String,
    pub currency: String,
    pub to_address: String,
    pub amount: Decimal,
    pub fee: Option<Decimal>,
    pub net_amount: Decimal,
    pub status: String,
    pub tx_hash: Option<String>,
    pub blockchain_confirmations: Option<i32>,
    pub required_confirmations: i32,
    pub metadata: Option<String>,
    pub error_message: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub processed_at: Option<DateTimeWithTimeZone>,
    pub confirmed_at: Option<DateTimeWithTimeZone>,
    pub updated_at: DateTimeWithTimeZone,
    pub broadcast_at: Option<DateTimeWithTimeZone>,
    pub failed_at: Option<DateTimeWithTimeZone>,
    pub failure_reason: Option<String>,
    // Safe withdrawal fields
    pub finality_required: i32,
    pub finality_reached_at: Option<DateTimeWithTimeZone>,
    pub replaced_by_tx: Option<String>,
    pub reorg_depth: i32,
    pub lifecycle_state: String,
    pub withdrawal_funds_state: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::merchant::Entity",
        from = "Column::MerchantId",
        to = "super::merchant::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Merchant,
    #[sea_orm(
        belongs_to = "super::wallet::Entity",
        from = "Column::WalletId",
        to = "super::wallet::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Wallet,
}

impl Related<super::merchant::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Merchant.def()
    }
}

impl Related<super::wallet::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Wallet.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

impl Model {
    /// Check if withdrawal can be cancelled
    pub fn can_be_cancelled(&self) -> bool {
        // Can only cancel withdrawals that are pending or processing
        matches!(self.status.as_str(), "pending" | "processing")
    }

    /// Get the withdrawal funds state as enum
    pub fn get_funds_state(&self) -> crate::shared::models::withdrawal_state::WithdrawalFundsState {
        self.withdrawal_funds_state
            .parse()
            .unwrap_or(crate::shared::models::withdrawal_state::WithdrawalFundsState::Unlocked)
    }

    /// Get the lifecycle state as enum
    pub fn get_lifecycle_state(
        &self,
    ) -> crate::shared::models::withdrawal_state::WithdrawalLifecycleState {
        self.lifecycle_state
            .parse()
            .unwrap_or(crate::shared::models::withdrawal_state::WithdrawalLifecycleState::Quoted)
    }

    /// Check if finality has been reached
    pub fn has_reached_finality(&self) -> bool {
        self.finality_reached_at.is_some()
            && self.blockchain_confirmations.unwrap_or(0) >= self.finality_required
    }

    /// Check if withdrawal is in a terminal state
    pub fn is_terminal(&self) -> bool {
        self.get_lifecycle_state().is_terminal()
    }

    /// Check if withdrawal is actively being processed
    pub fn is_active(&self) -> bool {
        self.get_lifecycle_state().is_active()
    }

    /// Check if funds are currently locked
    pub fn has_locked_funds(&self) -> bool {
        self.get_funds_state().is_locked()
    }

    /// Get confirmation progress as ratio (0.0 to 1.0)
    pub fn confirmation_progress(&self) -> f64 {
        if self.finality_required <= 0 {
            return 1.0;
        }
        let confirmations = self.blockchain_confirmations.unwrap_or(0).max(0);
        (confirmations as f64 / self.finality_required as f64).min(1.0)
    }

    /// Check if transaction might have been reorged
    pub fn has_potential_reorg(&self) -> bool {
        self.reorg_depth > 0
    }
}
